version: '2'

services:
  web2:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '7777:7777'
    links:
      - mongoo

  mongoo:
    image: mongo:3.0
    ports:
      - '27017:27017'
    volumes:
      - /data/db
